-- Migration: dom_schema_init
-- Description: Creación de tablas, RLS, triggers, RPCs y tabla dedicada dom_payment_priorities aislada exclusivamente bajo el namespace dom_

-- 1. Habilitar extensión uuid si no existe
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Asegurar existencia de tablas base dom_
CREATE TABLE IF NOT EXISTS dom_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_padre_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL,
  opening_balance NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  color TEXT,
  is_archived BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID,
  updated_by UUID,
  unidad_negocio_id BIGINT
);

CREATE TABLE IF NOT EXISTS dom_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  persona_padre_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  direction TEXT NOT NULL,
  color TEXT,
  is_archived BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID,
  updated_by UUID,
  unidad_negocio_id BIGINT
);

CREATE TABLE IF NOT EXISTS dom_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  account_id BIGINT REFERENCES dom_accounts(id),
  category_id BIGINT REFERENCES dom_categories(id),
  direction TEXT NOT NULL CHECK (direction IN ('income', 'expense')),
  amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  description TEXT NOT NULL,
  occurred_on DATE NOT NULL DEFAULT CURRENT_DATE,
  payment_method TEXT NOT NULL DEFAULT 'cash',
  status TEXT NOT NULL DEFAULT 'completed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID,
  unidad_negocio_id BIGINT
);

CREATE TABLE IF NOT EXISTS dom_projected_transactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  label TEXT NOT NULL,
  category_id BIGINT REFERENCES dom_categories(id),
  flow_type TEXT NOT NULL CHECK (flow_type IN ('income', 'expense', 'info')),
  origin_amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  default_method TEXT NOT NULL DEFAULT 'cash',
  due_rule_mode TEXT NOT NULL DEFAULT 'day',
  due_day INTEGER NOT NULL DEFAULT 10,
  due_end_day INTEGER NOT NULL DEFAULT 10,
  month_index INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_receivables (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  debtor_name TEXT NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  due_date DATE,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_debts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  creditor_name TEXT NOT NULL,
  debt_type TEXT NOT NULL,
  total_principal NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  arrears_balance NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  monthly_installment NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  interest_rate_monthly NUMERIC(8,4) NOT NULL DEFAULT 0.0000,
  priority INTEGER NOT NULL DEFAULT 99,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_debt_installments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  debt_id UUID NOT NULL REFERENCES dom_debts(id) ON DELETE CASCADE,
  installment_number INTEGER NOT NULL,
  due_date DATE NOT NULL,
  amount_principal NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  amount_interest NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_debt_payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  debt_id UUID NOT NULL REFERENCES dom_debts(id) ON DELETE CASCADE,
  amount_paid NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  payment_date DATE NOT NULL DEFAULT CURRENT_DATE,
  allocated_to_principal NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  allocated_to_arrears NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  allocated_to_interest NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_cards (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  closing_day INTEGER NOT NULL DEFAULT 25,
  due_day INTEGER NOT NULL DEFAULT 10,
  credit_limit NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_card_purchases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  card_id UUID NOT NULL REFERENCES dom_cards(id) ON DELETE CASCADE,
  purchase_date DATE NOT NULL DEFAULT CURRENT_DATE,
  description TEXT NOT NULL,
  total_amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  installments_count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_card_installments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  purchase_id UUID NOT NULL REFERENCES dom_card_purchases(id) ON DELETE CASCADE,
  installment_number INTEGER NOT NULL,
  amount NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  statement_period TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_payment_priorities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('card', 'expense', 'tax', 'mortgage', 'loan')),
  entity_identifier TEXT NOT NULL,
  label TEXT NOT NULL,
  priority_order INTEGER NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT dom_payment_priorities_tenant_entity_unique UNIQUE(persona_padre_id, entity_identifier)
);

CREATE TABLE IF NOT EXISTS dom_parameters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  param_key TEXT NOT NULL,
  param_value JSONB NOT NULL,
  description TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT dom_parameters_key_tenant_unique UNIQUE(persona_padre_id, param_key)
);

CREATE TABLE IF NOT EXISTS dom_monthly_parameters (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  month_period TEXT NOT NULL,
  ipc_rate NUMERIC(8,4) NOT NULL DEFAULT 0.0100,
  rent_amount NUMERIC(18,2) NOT NULL DEFAULT 550000.00,
  monotributo_amount NUMERIC(18,2) NOT NULL DEFAULT 91714.67,
  business_extra_growth NUMERIC(18,2) NOT NULL DEFAULT 200000.00,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT dom_monthly_parameters_month_tenant_unique UNIQUE(persona_padre_id, month_period)
);

CREATE TABLE IF NOT EXISTS dom_scenarios (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  include_extra_income BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_scenario_results (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  scenario_id UUID NOT NULL REFERENCES dom_scenarios(id) ON DELETE CASCADE,
  month_period TEXT NOT NULL,
  projected_income NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  projected_expense NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  monthly_gap NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  accumulated_gap NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  problematic_debt_stock NUMERIC(18,2) NOT NULL DEFAULT 0.00,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS dom_audit_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  persona_padre_id INTEGER NOT NULL,
  user_id UUID,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL,
  previous_value JSONB,
  new_value JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 3. Habilitar RLS en todas las tablas dom_
ALTER TABLE dom_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_projected_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_receivables ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_debt_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_debt_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_card_purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_card_installments ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_payment_priorities ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_monthly_parameters ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_scenario_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE dom_audit_log ENABLE ROW LEVEL SECURITY;

-- 4. RPC Helper para verificar persona_padre_id en RLS
CREATE OR REPLACE FUNCTION dom_current_persona_padre_id()
RETURNS INTEGER AS $$
BEGIN
  RETURN COALESCE((current_setting('app.current_persona_padre_id', true))::integer, 1);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Crear Policies de RLS aisladas (dom_*)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'dom_payment_priorities_tenant_policy') THEN
    CREATE POLICY dom_payment_priorities_tenant_policy ON dom_payment_priorities
      USING (persona_padre_id = dom_current_persona_padre_id());
  END IF;
END $$;

-- 6. Insertar Semillas de Ranking Predeterminado en dom_payment_priorities
INSERT INTO dom_payment_priorities (persona_padre_id, entity_type, entity_identifier, label, priority_order)
VALUES
  (1, 'card', 'supervielle_card', 'Tarjeta Supervielle', 1),
  (1, 'expense', 'bruno_medical', 'Médicos Bruno', 2),
  (1, 'tax', 'monotributo', 'Monotributo corriente', 3),
  (1, 'mortgage', 'hipotecario_1', 'Hipotecario 1', 4),
  (1, 'mortgage', 'hipotecario_2', 'Hipotecario 2', 5),
  (1, 'loan', 'supervielle_loan', 'Préstamo Supervielle', 6)
ON CONFLICT (persona_padre_id, entity_identifier) DO NOTHING;

-- 7. Función RPC dom_allocate_payment
DO $$
BEGIN
  DROP FUNCTION IF EXISTS dom_allocate_payment(INTEGER, UUID, NUMERIC);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

CREATE OR REPLACE FUNCTION dom_allocate_payment(
  p_persona_padre_id INTEGER,
  p_debt_id UUID,
  p_amount NUMERIC
)
RETURNS JSONB AS $$
DECLARE
  v_debt dom_debts%ROWTYPE;
  v_allocated_arrears NUMERIC(18,2) := 0.00;
  v_allocated_principal NUMERIC(18,2) := 0.00;
  v_remaining NUMERIC(18,2) := COALESCE(p_amount, 0.00);
BEGIN
  SELECT * INTO v_debt FROM dom_debts 
  WHERE id = p_debt_id AND persona_padre_id = p_persona_padre_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Deuda no encontrada para el tenant especificado';
  END IF;

  IF v_debt.arrears_balance > 0 AND v_remaining > 0 THEN
    IF v_remaining >= v_debt.arrears_balance THEN
      v_allocated_arrears := v_debt.arrears_balance;
      v_remaining := v_remaining - v_debt.arrears_balance;
    ELSE
      v_allocated_arrears := v_remaining;
      v_remaining := 0.00;
    END IF;
  END IF;

  IF v_remaining > 0 THEN
    v_allocated_principal := v_remaining;
  END IF;

  INSERT INTO dom_debt_payments (
    persona_padre_id,
    debt_id,
    amount_paid,
    payment_date,
    allocated_to_principal,
    allocated_to_arrears
  ) VALUES (
    p_persona_padre_id,
    p_debt_id,
    p_amount,
    CURRENT_DATE,
    v_allocated_principal,
    v_allocated_arrears
  );

  UPDATE dom_debts
  SET 
    arrears_balance = GREATEST(0.00, arrears_balance - v_allocated_arrears),
    total_principal = GREATEST(0.00, total_principal - v_allocated_principal)
  WHERE id = p_debt_id AND persona_padre_id = p_persona_padre_id;

  INSERT INTO dom_audit_log (
    persona_padre_id,
    user_id,
    entity_type,
    entity_id,
    action,
    new_value
  ) VALUES (
    p_persona_padre_id,
    auth.uid(),
    'dom_debts',
    p_debt_id::text,
    'ALLOCATE_PAYMENT',
    jsonb_build_object(
      'amount_paid', p_amount,
      'allocated_to_arrears', v_allocated_arrears,
      'allocated_to_principal', v_allocated_principal
    )
  );

  RETURN jsonb_build_object(
    'success', true,
    'allocated_arrears', v_allocated_arrears,
    'allocated_principal', v_allocated_principal
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
