-- Agenor Domestic: reconcile and harden the live dom_ contract.
-- Scope: only public.dom_* objects owned by Agenor Domestic.

do $$
begin
  if to_regprocedure('private.tenant_can_access(integer)') is null then
    raise exception 'Falta la autoridad tenant compartida private.tenant_can_access(integer)';
  end if;
end
$$;

create table if not exists public.dom_entries (
  id bigint generated by default as identity primary key,
  persona_padre_id integer not null,
  account_id bigint not null references public.dom_accounts(id),
  category_id bigint references public.dom_categories(id),
  direction text not null check (direction in ('income', 'expense')),
  flow_status text not null check (flow_status in ('real', 'projected')),
  amount numeric(14, 2) not null check (amount > 0),
  description text not null check (length(btrim(description)) > 0),
  occurred_on date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid default auth.uid(),
  updated_by uuid default auth.uid(),
  unidad_negocio_id bigint
);

do $$
begin
  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conname = 'dom_accounts_persona_name_key'
      and conrelid = 'public.dom_accounts'::regclass
  ) then
    alter table public.dom_accounts
      add constraint dom_accounts_persona_name_key unique (persona_padre_id, name);
  end if;

  if not exists (
    select 1 from pg_catalog.pg_constraint
    where conname = 'dom_categories_persona_name_direction_key'
      and conrelid = 'public.dom_categories'::regclass
  ) then
    alter table public.dom_categories
      add constraint dom_categories_persona_name_direction_key
      unique (persona_padre_id, name, direction);
  end if;
end
$$;

create index if not exists dom_accounts_persona_active_idx
  on public.dom_accounts (persona_padre_id, is_archived);
create index if not exists dom_categories_persona_active_idx
  on public.dom_categories (persona_padre_id, is_archived, direction);
create index if not exists dom_entries_persona_date_idx
  on public.dom_entries (persona_padre_id, occurred_on desc);
create index if not exists dom_entries_account_idx
  on public.dom_entries (account_id);
create index if not exists dom_entries_category_idx
  on public.dom_entries (category_id);

create or replace function public.dom_current_persona_padre_id()
returns integer
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_auth_uid uuid := auth.uid();
  v_persona_padre_id integer;
begin
  if v_auth_uid is null then
    raise exception 'Usuario no autenticado' using errcode = '42501';
  end if;

  select u.persona_padre_id
    into v_persona_padre_id
  from public.usuarios u
  where u.auth_uuid = v_auth_uid
    and coalesce(u.activo, true)
    and u.persona_padre_id is not null
  order by u.id
  limit 1;

  if v_persona_padre_id is null then
    select ue.persona_padre_id
      into v_persona_padre_id
    from public.usuarios_empresas ue
    where ue.usuario_id = v_auth_uid
      and coalesce(ue.es_activo, true)
    order by ue.persona_padre_id
    limit 1;
  end if;

  if v_persona_padre_id is null
     or not private.tenant_can_access(v_persona_padre_id) then
    raise exception 'No hay un contexto personal activo para el usuario autenticado'
      using errcode = '42501';
  end if;

  return v_persona_padre_id;
end;
$$;

create or replace function public.dom_assert_tenant_access(p_persona_padre_id integer)
returns void
language plpgsql
stable
security definer
set search_path to ''
as $$
begin
  if not private.tenant_can_access(p_persona_padre_id) then
    raise exception 'No tiene acceso al contexto solicitado' using errcode = '42501';
  end if;
end;
$$;

create or replace function public.dom_set_audit_fields()
returns trigger
language plpgsql
security invoker
set search_path to ''
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.uid();
  return new;
end;
$$;

drop trigger if exists dom_accounts_set_audit_fields on public.dom_accounts;
create trigger dom_accounts_set_audit_fields
before update on public.dom_accounts
for each row execute function public.dom_set_audit_fields();

drop trigger if exists dom_categories_set_audit_fields on public.dom_categories;
create trigger dom_categories_set_audit_fields
before update on public.dom_categories
for each row execute function public.dom_set_audit_fields();

drop trigger if exists dom_entries_set_audit_fields on public.dom_entries;
create trigger dom_entries_set_audit_fields
before update on public.dom_entries
for each row execute function public.dom_set_audit_fields();

create or replace function public.dom_context_get(p_persona_padre_id integer default null)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_persona_padre_id integer;
begin
  if p_persona_padre_id is null then
    v_persona_padre_id := public.dom_current_persona_padre_id();
  else
    perform public.dom_assert_tenant_access(p_persona_padre_id);
    v_persona_padre_id := p_persona_padre_id;
  end if;

  return jsonb_build_object('persona_padre_id', v_persona_padre_id);
end;
$$;

create or replace function public.dom_catalog_get(p_persona_padre_id integer)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);
  return jsonb_build_object(
    'accounts', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', a.id,
        'name', a.name,
        'kind', a.kind,
        'opening_balance', a.opening_balance,
        'color', a.color
      ) order by a.name)
      from public.dom_accounts a
      where a.persona_padre_id = p_persona_padre_id
        and not a.is_archived
    ), '[]'::jsonb),
    'categories', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', c.id,
        'name', c.name,
        'direction', c.direction,
        'color', c.color
      ) order by c.direction, c.name)
      from public.dom_categories c
      where c.persona_padre_id = p_persona_padre_id
        and not c.is_archived
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.dom_onboarding_complete(
  p_persona_padre_id integer,
  p_account_name text,
  p_opening_balance numeric
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_account_id bigint;
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);
  if length(btrim(coalesce(p_account_name, ''))) = 0 then
    raise exception 'El nombre de la cuenta es obligatorio' using errcode = '22023';
  end if;

  insert into public.dom_accounts (
    persona_padre_id, name, kind, opening_balance, created_by, updated_by
  ) values (
    p_persona_padre_id, btrim(p_account_name), 'cash',
    coalesce(p_opening_balance, 0), auth.uid(), auth.uid()
  )
  on conflict (persona_padre_id, name) do update
    set updated_at = public.dom_accounts.updated_at
  returning id into v_account_id;

  insert into public.dom_categories (
    persona_padre_id, name, direction, color, created_by, updated_by
  ) values
    (p_persona_padre_id, 'Trabajo', 'income', '#3D8B6D', auth.uid(), auth.uid()),
    (p_persona_padre_id, 'Hogar', 'expense', '#D97757', auth.uid(), auth.uid()),
    (p_persona_padre_id, 'Comida', 'expense', '#E6A23C', auth.uid(), auth.uid()),
    (p_persona_padre_id, 'Transporte', 'expense', '#6376B8', auth.uid(), auth.uid()),
    (p_persona_padre_id, 'Otros', 'expense', '#75808A', auth.uid(), auth.uid())
  on conflict (persona_padre_id, name, direction) do nothing;

  return jsonb_build_object('account_id', v_account_id);
end;
$$;

create or replace function public.dom_account_create(
  p_persona_padre_id integer,
  p_name text,
  p_kind text,
  p_opening_balance numeric default 0
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_account_id bigint;
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);
  if length(btrim(coalesce(p_name, ''))) = 0 then
    raise exception 'El nombre de la cuenta es obligatorio' using errcode = '22023';
  end if;

  insert into public.dom_accounts (
    persona_padre_id, name, kind, opening_balance, created_by, updated_by
  ) values (
    p_persona_padre_id,
    btrim(p_name),
    coalesce(p_kind, 'cash'),
    coalesce(p_opening_balance, 0),
    auth.uid(),
    auth.uid()
  )
  returning id into v_account_id;

  return jsonb_build_object('id', v_account_id);
end;
$$;

create or replace function public.dom_category_create(
  p_persona_padre_id integer,
  p_name text,
  p_direction text,
  p_color text default '#75808A'
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_category_id bigint;
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);
  if length(btrim(coalesce(p_name, ''))) = 0 then
    raise exception 'El nombre de la categoria es obligatorio' using errcode = '22023';
  end if;

  insert into public.dom_categories (
    persona_padre_id, name, direction, color, created_by, updated_by
  ) values (
    p_persona_padre_id,
    btrim(p_name),
    p_direction,
    coalesce(nullif(btrim(p_color), ''), '#75808A'),
    auth.uid(),
    auth.uid()
  )
  returning id into v_category_id;

  return jsonb_build_object('id', v_category_id);
end;
$$;

create or replace function public.dom_entry_create(
  p_persona_padre_id integer,
  p_account_id bigint,
  p_category_id bigint,
  p_direction text,
  p_flow_status text,
  p_amount numeric,
  p_description text,
  p_occurred_on date
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_entry_id bigint;
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);

  if p_amount is null or p_amount <= 0 then
    raise exception 'El importe debe ser mayor a cero' using errcode = '22023';
  end if;
  if length(btrim(coalesce(p_description, ''))) = 0 then
    raise exception 'La descripcion es obligatoria' using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.dom_accounts a
    where a.id = p_account_id
      and a.persona_padre_id = p_persona_padre_id
      and not a.is_archived
  ) then
    raise exception 'La cuenta no pertenece al contexto activo' using errcode = '42501';
  end if;
  if p_category_id is not null and not exists (
    select 1 from public.dom_categories c
    where c.id = p_category_id
      and c.persona_padre_id = p_persona_padre_id
      and not c.is_archived
      and c.direction = p_direction
  ) then
    raise exception 'La categoria no pertenece al contexto activo' using errcode = '42501';
  end if;

  insert into public.dom_entries (
    persona_padre_id, account_id, category_id, direction, flow_status,
    amount, description, occurred_on, created_by, updated_by
  ) values (
    p_persona_padre_id, p_account_id, p_category_id, p_direction, p_flow_status,
    p_amount, btrim(p_description), coalesce(p_occurred_on, current_date),
    auth.uid(), auth.uid()
  )
  returning id into v_entry_id;

  return jsonb_build_object('id', v_entry_id);
end;
$$;

create or replace function public.dom_entries_list(
  p_persona_padre_id integer,
  p_limit integer default 50
)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);
  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'id', e.id,
      'account_id', e.account_id,
      'account_name', a.name,
      'category_id', e.category_id,
      'category_name', c.name,
      'direction', e.direction,
      'flow_status', e.flow_status,
      'amount', e.amount,
      'description', e.description,
      'occurred_on', e.occurred_on
    ) order by e.occurred_on desc, e.id desc)
    from (
      select * from public.dom_entries
      where persona_padre_id = p_persona_padre_id
      order by occurred_on desc, id desc
      limit greatest(1, least(coalesce(p_limit, 50), 100))
    ) e
    join public.dom_accounts a
      on a.id = e.account_id
     and a.persona_padre_id = p_persona_padre_id
    left join public.dom_categories c
      on c.id = e.category_id
     and c.persona_padre_id = p_persona_padre_id
  ), '[]'::jsonb);
end;
$$;

create or replace function public.dom_dashboard_summary(
  p_persona_padre_id integer,
  p_end_date date default (current_date + 30)
)
returns jsonb
language plpgsql
stable
security definer
set search_path to ''
as $$
declare
  v_current_balance numeric(14, 2);
  v_month_income numeric(14, 2);
  v_month_expense numeric(14, 2);
  v_projected_balance numeric(14, 2);
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);

  select
    coalesce((select sum(a.opening_balance)
      from public.dom_accounts a
      where a.persona_padre_id = p_persona_padre_id and not a.is_archived), 0)
    + coalesce((select sum(case when e.direction = 'income' then e.amount else -e.amount end)
      from public.dom_entries e
      where e.persona_padre_id = p_persona_padre_id
        and e.flow_status = 'real'
        and e.occurred_on <= current_date), 0)
  into v_current_balance;

  select
    coalesce(sum(case when direction = 'income' then amount else 0 end), 0),
    coalesce(sum(case when direction = 'expense' then amount else 0 end), 0)
  into v_month_income, v_month_expense
  from public.dom_entries
  where persona_padre_id = p_persona_padre_id
    and flow_status = 'real'
    and occurred_on >= date_trunc('month', current_date)::date
    and occurred_on <= current_date;

  select v_current_balance
    + coalesce(sum(case when direction = 'income' then amount else -amount end), 0)
  into v_projected_balance
  from public.dom_entries
  where persona_padre_id = p_persona_padre_id
    and flow_status = 'projected'
    and occurred_on > current_date
    and occurred_on <= greatest(p_end_date, current_date);

  return jsonb_build_object(
    'current_balance', v_current_balance,
    'month_income', v_month_income,
    'month_expense', v_month_expense,
    'projected_balance', v_projected_balance,
    'upcoming', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', e.id,
        'description', e.description,
        'amount', e.amount,
        'direction', e.direction,
        'flow_status', e.flow_status,
        'occurred_on', e.occurred_on,
        'account_name', a.name,
        'category_name', c.name
      ) order by e.occurred_on, e.id)
      from (
        select * from public.dom_entries
        where persona_padre_id = p_persona_padre_id
          and occurred_on >= current_date
          and occurred_on <= greatest(p_end_date, current_date)
        order by occurred_on, id
        limit 8
      ) e
      join public.dom_accounts a
        on a.id = e.account_id
       and a.persona_padre_id = p_persona_padre_id
      left join public.dom_categories c
        on c.id = e.category_id
       and c.persona_padre_id = p_persona_padre_id
    ), '[]'::jsonb),
    'weeks', coalesce((
      select jsonb_agg(jsonb_build_object(
        'week_start', w.week_start,
        'net_amount', coalesce((
          select sum(case when e.direction = 'income' then e.amount else -e.amount end)
          from public.dom_entries e
          where e.persona_padre_id = p_persona_padre_id
            and e.flow_status = 'projected'
            and e.occurred_on >= w.week_start
            and e.occurred_on < w.week_start + 7
        ), 0)
      ) order by w.week_start)
      from generate_series(
        date_trunc('week', current_date)::date,
        least(
          date_trunc('week', greatest(p_end_date, current_date))::date,
          date_trunc('week', current_date)::date + 28
        ),
        interval '7 days'
      ) as w(week_start)
    ), '[]'::jsonb)
  );
end;
$$;

create or replace function public.dom_allocate_payment(
  p_persona_padre_id integer,
  p_debt_id uuid,
  p_amount numeric
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_debt public.dom_debts%rowtype;
  v_allocated_arrears numeric(18, 2) := 0;
  v_allocated_principal numeric(18, 2) := 0;
  v_remaining numeric(18, 2);
begin
  perform public.dom_assert_tenant_access(p_persona_padre_id);
  if p_amount is null or p_amount <= 0 then
    raise exception 'El importe debe ser mayor a cero' using errcode = '22023';
  end if;

  select * into v_debt
  from public.dom_debts
  where id = p_debt_id
    and persona_padre_id = p_persona_padre_id
  for update;

  if not found then
    raise exception 'Deuda no encontrada para el tenant especificado' using errcode = 'P0002';
  end if;
  if p_amount > v_debt.arrears_balance + v_debt.total_principal then
    raise exception 'El importe supera el saldo total de la deuda' using errcode = '22023';
  end if;

  v_remaining := p_amount;
  v_allocated_arrears := least(v_debt.arrears_balance, v_remaining);
  v_remaining := v_remaining - v_allocated_arrears;
  v_allocated_principal := least(v_debt.total_principal, v_remaining);

  insert into public.dom_debt_payments (
    persona_padre_id,
    debt_id,
    amount_paid,
    payment_date,
    allocated_to_principal,
    allocated_to_arrears
  ) values (
    p_persona_padre_id,
    p_debt_id,
    p_amount,
    current_date,
    v_allocated_principal,
    v_allocated_arrears
  );

  update public.dom_debts
  set arrears_balance = arrears_balance - v_allocated_arrears,
      total_principal = total_principal - v_allocated_principal
  where id = p_debt_id
    and persona_padre_id = p_persona_padre_id;

  insert into public.dom_audit_log (
    persona_padre_id,
    user_id,
    entity_type,
    entity_id,
    action,
    new_value
  ) values (
    p_persona_padre_id,
    auth.uid(),
    'dom_debts',
    p_debt_id::text,
    'ALLOCATE_PAYMENT',
    jsonb_build_object(
      'amount_paid', p_amount,
      'allocated_to_arrears', v_allocated_arrears,
      'allocated_to_principal', v_allocated_principal
    )
  );

  return jsonb_build_object(
    'success', true,
    'allocated_arrears', v_allocated_arrears,
    'allocated_principal', v_allocated_principal,
    'remaining_arrears', v_debt.arrears_balance - v_allocated_arrears,
    'remaining_principal', v_debt.total_principal - v_allocated_principal
  );
end;
$$;

alter table public.dom_accounts enable row level security;
alter table public.dom_categories enable row level security;
alter table public.dom_entries enable row level security;
alter table public.dom_transactions enable row level security;
alter table public.dom_projected_transactions enable row level security;
alter table public.dom_receivables enable row level security;
alter table public.dom_debts enable row level security;
alter table public.dom_debt_installments enable row level security;
alter table public.dom_debt_payments enable row level security;
alter table public.dom_cards enable row level security;
alter table public.dom_card_purchases enable row level security;
alter table public.dom_card_installments enable row level security;
alter table public.dom_payment_priorities enable row level security;
alter table public.dom_parameters enable row level security;
alter table public.dom_monthly_parameters enable row level security;
alter table public.dom_scenarios enable row level security;
alter table public.dom_scenario_results enable row level security;
alter table public.dom_audit_log enable row level security;

drop policy if exists dom_accounts_select_own on public.dom_accounts;
create policy dom_accounts_select_own on public.dom_accounts
for select to authenticated
using ((select private.tenant_can_access(persona_padre_id)));

drop policy if exists dom_categories_select_own on public.dom_categories;
create policy dom_categories_select_own on public.dom_categories
for select to authenticated
using ((select private.tenant_can_access(persona_padre_id)));

drop policy if exists dom_entries_select_own on public.dom_entries;
create policy dom_entries_select_own on public.dom_entries
for select to authenticated
using ((select private.tenant_can_access(persona_padre_id)));

drop policy if exists dom_payment_priorities_tenant_policy
  on public.dom_payment_priorities;

revoke all on table
  public.dom_accounts,
  public.dom_categories,
  public.dom_entries,
  public.dom_transactions,
  public.dom_projected_transactions,
  public.dom_receivables,
  public.dom_debts,
  public.dom_debt_installments,
  public.dom_debt_payments,
  public.dom_cards,
  public.dom_card_purchases,
  public.dom_card_installments,
  public.dom_payment_priorities,
  public.dom_parameters,
  public.dom_monthly_parameters,
  public.dom_scenarios,
  public.dom_scenario_results,
  public.dom_audit_log
from public, anon, authenticated;

grant select on table
  public.dom_accounts,
  public.dom_categories,
  public.dom_entries
to authenticated;

revoke execute on function public.dom_current_persona_padre_id() from public, anon, authenticated;
revoke execute on function public.dom_assert_tenant_access(integer) from public, anon, authenticated;
revoke execute on function public.dom_set_audit_fields() from public, anon, authenticated;
revoke execute on function public.dom_context_get(integer) from public, anon, authenticated;
revoke execute on function public.dom_catalog_get(integer) from public, anon, authenticated;
revoke execute on function public.dom_onboarding_complete(integer, text, numeric) from public, anon, authenticated;
revoke execute on function public.dom_account_create(integer, text, text, numeric) from public, anon, authenticated;
revoke execute on function public.dom_category_create(integer, text, text, text) from public, anon, authenticated;
revoke execute on function public.dom_entry_create(integer, bigint, bigint, text, text, numeric, text, date) from public, anon, authenticated;
revoke execute on function public.dom_entries_list(integer, integer) from public, anon, authenticated;
revoke execute on function public.dom_dashboard_summary(integer, date) from public, anon, authenticated;
revoke execute on function public.dom_allocate_payment(integer, uuid, numeric) from public, anon, authenticated;

grant execute on function
  public.dom_context_get(integer),
  public.dom_catalog_get(integer),
  public.dom_onboarding_complete(integer, text, numeric),
  public.dom_account_create(integer, text, text, numeric),
  public.dom_category_create(integer, text, text, text),
  public.dom_entry_create(integer, bigint, bigint, text, text, numeric, text, date),
  public.dom_entries_list(integer, integer),
  public.dom_dashboard_summary(integer, date),
  public.dom_allocate_payment(integer, uuid, numeric)
to authenticated, service_role;
